name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16, 1.17]
    steps:
      - name: Set up Go
        uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57 #v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2.3.4
      - name: Install Linters
        run: "curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.44.2"
      - name: Build
        run: go build ./...
      - name: Lint
        run: |
          golangci-lint run --disable-all --deadline=10m --enable=gofmt --enable=goimports --enable=gosimple --enable=unconvert --enable=ineffassign --enable=govet --enable=structcheck
      - name: Test
        run: |
          go test -v ./...
          ./test.sh
